DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3MzA5NjkxMjYsInVzZXJJZCI6MX0.D6uVcAJoi_VcvlEh7Vr8vwvPos3Gsmn7mVukKyr_9rc