PUT http://localhost:8080/events/2
Content-Type: application/json

{
    "name" : "GO - Event 1 updated",
    "description" : "Event 1 was updated",
    "location" : "some location updated",
    "dateTime" : "2025-02-02T15:30:00Z"
}